apiVersion: v1
kind: ConfigMap
metadata:
  name: techcorp-config
data:
  environment: "production"
  log_level: "INFO"
  max_workers: "4"
  kafka_bootstrap_servers: "kafka-service:9092"
  frontend_url: "http://techcorp-frontend-service"